# Generated by Django 5.2.6 on 2025-10-16 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_page_options_remove_page_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
